### ISSUE TITLE
can you help me , update  switching-to-angular2   for angular2 final 

### ISSUE THREAD

**Issue by smile2014** [mgechev/switching-to-angular2#17]

**Comment by mgechev** [comment]
The published edition explores RC.4 where the biggest difference from final is the lack of `NgModule`.

In order to be consistent with the published content the repository will not be update to final. If you need a starter project I'd recommend you [angular2-seed](https://github.com/mgechev/angular2-seed) which is used as core for this repo.

**Comment by smile2014** [comment]
thank you @mgechev
